// permissions.ts

export const PERMISSIONS = {
  admin: {
    menus: [
      {
        name: "admin.menu.dashboard",
        description: "Access to the main dashboard view",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.dispute",
        description: "Access to dispute management and resolution view",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.paymentlinks",
        description: "Access to payment links management section",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.transactions",
        description: "Access to transactions menu",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.wallets",
        description: "Access to wallets management section",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.reports",
        description: "Access to reports and analytics menu",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.notifications",
        description: "Access to notifications management menu",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.businessprofiles",
        description: "Access to business profiles section",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.banksettings",
        description: "Access to bank settings",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.usermanagement",
        description: "Access to user management",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.studentmanagement",
        description: "Access to student management",
        type: "menu",
        category: "admin",
      },
      {
        name: "admin.menu.guardianmanagement",
        description: "Access to guardian management",
        type: "menu",
        category: "admin",
      },
    ],
    actions: [
      {
        name: "admin.dataanalytics.view",
        description: "View analytics",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.payment_link.generate",
        description: "Generate payment links",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.manualreceipt.create",
        description: "Create manual receipts",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.payment_link.view",
        description: "View payment links",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.payment_link.update",
        description: "Update payment links",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.dispute.read",
        description: "Read disputes",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.dispute.create",
        description: "Create disputes",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.initiate_payment.create",
        description: "Initiate payments",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.recent_transactions.view",
        description: "View recent transactions",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.transaction_details.view",
        description: "View transaction details",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.transaction_details.export",
        description: "Export transaction details",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.receipt.create",
        description: "Create receipts",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.receipt.download",
        description: "Download receipts",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.receipt.send",
        description: "Send receipts",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.wallet.initiate_settlement",
        description: "Initiate settlement",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.report_analytics.view",
        description: "View reports",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.report_analytics.export",
        description: "Export reports",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.report_analytics.email",
        description: "Email reports",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification_history.view",
        description: "View notification history",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification.save_template",
        description: "Save templates",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification_template.create",
        description: "Create templates",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification_template.preview",
        description: "Preview templates",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification_template.enable",
        description: "Enable templates",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.notification_template.disable",
        description: "Disable templates",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.business_profile.update",
        description: "Update business profile",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.bank_settings_settlement_history.view",
        description: "View settlement history",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.bank_settings_bank_account.create",
        description: "Create bank account",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.bank_settings_bank_account.delete",
        description: "Delete bank account",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management_activity_log.view",
        description: "View activity log",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management.create_user",
        description: "Create user",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management.update_user",
        description: "Update user",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management.delete_user",
        description: "Delete user",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management.read_user",
        description: "Read user",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.user_management.search_user",
        description: "Search user",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.student_management.create_student",
        description: "Create student",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.student_management.read_student",
        description: "Read student",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.student_management.update_student",
        description: "Update student",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.student_management.delete_student",
        description: "Delete student",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.student_management.search_student",
        description: "Search student",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.guardian_management.create_guardian",
        description: "Create guardian",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.guardian_management.read_guardian",
        description: "Read guardian",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.guardian_management.update_guardian",
        description: "Update guardian",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.guardian_management.delete_guardian",
        description: "Delete guardian",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.guardian_management.search_guardian",
        description: "Search guardian",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.payment_item.create",
        description: "Create payment items",
        type: "action",
        category: "admin",
      },
      {
        name: "admin.payment_item.approve",
        description: "Approve payment items",
        type: "action",
        category: "admin",
      },
    ],
  },
  students: {
    menus: [
      {
        name: "student.menu.dashboard",
        description: "Dashboard",
        type: "menu",
        category: "student",
      },
      {
        name: "student.menu.invoices",
        description: "Invoices",
        type: "menu",
        category: "student",
      },
      {
        name: "student.menu.payments",
        description: "Payments",
        type: "menu",
        category: "student",
      },
      {
        name: "student.menu.paymenthistory",
        description: "Payment history",
        type: "menu",
        category: "student",
      },
      {
        name: "student.menu.paymentmethods",
        description: "Payment methods",
        type: "menu",
        category: "student",
      },
      {
        name: "student.menu.receipts",
        description: "Receipts",
        type: "menu",
        category: "student",
      },
    ],
    actions: [
      {
        name: "student.view_balance",
        description: "View balance",
        type: "action",
        category: "student",
      },
      {
        name: "student.view_outstanding_balance",
        description: "View outstanding balance",
        type: "action",
        category: "student",
      },
      {
        name: "student.view_invoice",
        description: "View invoices",
        type: "action",
        category: "student",
      },
      {
        name: "student.make_payment",
        description: "Make payment",
        type: "action",
        category: "student",
      },
      {
        name: "student.view_payment_history",
        description: "View payment history",
        type: "action",
        category: "student",
      },
      {
        name: "student.view_payment_schedule",
        description: "View payment schedule",
        type: "action",
        category: "student",
      },
      {
        name: "student.request_payment_plan",
        description: "Request payment plan",
        type: "action",
        category: "student",
      },
      {
        name: "student.view_payment_methods",
        description: "View payment methods",
        type: "action",
        category: "student",
      },
      {
        name: "student.add_payment_method",
        description: "Add payment method",
        type: "action",
        category: "student",
      },
      {
        name: "student.remove_payment_method",
        description: "Remove payment method",
        type: "action",
        category: "student",
      },
      {
        name: "student.download_receipt",
        description: "Download receipt",
        type: "action",
        category: "student",
      },
      {
        name: "student.dispute_payment",
        description: "Dispute payment",
        type: "action",
        category: "student",
      },
    ],
  },
  guardians: {
    menus: [
      {
        name: "guardian.menu.dashboard",
        description: "Dashboard",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.invoices",
        description: "Invoices",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.payments",
        description: "Payments",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.paymenthistory",
        description: "History",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.paymentmethods",
        description: "Methods",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.receipts",
        description: "Receipts",
        type: "menu",
        category: "guardian",
      },
      {
        name: "guardian.menu.linkedstudents",
        description: "Linked students",
        type: "menu",
        category: "guardian",
      },
    ],
    actions: [
      {
        name: "guardian.view_balance",
        description: "View balance",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_outstanding_balance",
        description: "Outstanding balance",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_invoice",
        description: "View invoice",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.make_payment",
        description: "Make payment",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_payment_history",
        description: "History",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_payment_schedule",
        description: "Schedule",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.request_payment_plan",
        description: "Request plan",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_payment_methods",
        description: "Methods",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.add_payment_method",
        description: "Add method",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.remove_payment_method",
        description: "Remove method",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.download_receipt",
        description: "Download receipt",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.dispute_payment",
        description: "Dispute payment",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.manage_linked_students",
        description: "Manage linked students",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_all_children_payments",
        description: "View all payments",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.view_consolidated_invoice",
        description: "View consolidated invoice",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.pay_on_behalf_of_multiple_students",
        description: "Bulk pay",
        type: "action",
        category: "guardian",
      },
      {
        name: "guardian.set_payment_reminders",
        description: "Set reminders",
        type: "action",
        category: "guardian",
      },
    ],
  },
  kolektSuperAdmin: {
    menus: [
      {
        name: "kolekt_super_admin.menu.dashboard",
        description: "Dashboard",
        type: "menu",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.menu.businesses",
        description: "Businesses",
        type: "menu",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.menu.businessconfiguration",
        description: "Business configuration",
        type: "menu",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.menu.businesscustomization",
        description: "Business customization",
        type: "menu",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.menu.adminmanagement",
        description: "Admin management",
        type: "menu",
        category: "kolektsuperadmin",
      },
    ],
    actions: [
      {
        name: "kolekt_super_admin.business.onboard",
        description: "Onboard business",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business.read",
        description: "Read business",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business.update",
        description: "Update business",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_configuration.update",
        description: "Configure business",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_customization.update",
        description: "Customize branding",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_admin.create",
        description: "Create business admin",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_admin.read",
        description: "Read business admin",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_admin.update",
        description: "Update business admin",
        type: "action",
        category: "kolektsuperadmin",
      },
      {
        name: "kolekt_super_admin.business_admin.delete",
        description: "Delete business admin",
        type: "action",
        category: "kolektsuperadmin",
      },
    ],
  },
} as const;