
export const guardians = [
  {
    firstName: "Chinedu",
    lastName: "Okoye",
    PhoneNumber: "+2348037001001",
    email: "chinedu.okoye@example.com",
    password: "Password123",
  },
  {
    firstName: "Funke",
    lastName: "Olawale",
    PhoneNumber: "+2348037001002",
    email: "funke.olawale@example.com",
    password: "Password123",
  },
  {
    firstName: "Ngozi",
    lastName: "Eze",
    PhoneNumber: "+2348037001003",
    email: "ngozi.eze@example.com",
    password: "Password123",
  },
  {
    firstName: "Emeka",
    lastName: "Obi",
    PhoneNumber: "+2348037001004",
    email: "emeka.obi@example.com",
    password: "Password123",
  },
  {
    firstName: "Amina",
    lastName: "Bello",
    PhoneNumber: "+2348037001005",
    email: "amina.bello@example.com",
    password: "Password123",
  },
  {
    firstName: "Grace",
    lastName: "Johnson",
    PhoneNumber: "+2348037001006",
    email: "grace.johnson@example.com",
    password: "Password123",
  },
  {
    firstName: "Ifeanyi",
    lastName: "Nwosu",
    PhoneNumber: "+2348037001007",
    email: "ifeanyi.nwosu@example.com",
    password: "Password123",
  },
  {
    firstName: "Patience",
    lastName: "Umeh",
    PhoneNumber: "+2348037001008",
    email: "patience.umeh@example.com",
    password: "Password123",
  },
  {
    firstName: "Abdul",
    lastName: "Musa",
    PhoneNumber: "+2348037001009",
    email: "abdul.musa@example.com",
    password: "Password123",
  },
  {
    firstName: "Ruth",
    lastName: "Adebayo",
    PhoneNumber: "+2348037001010",
    email: "ruth.adebayo@example.com",
    password: "Password123",
  },
  {
    firstName: "Samuel",
    lastName: "Ekanem",
    PhoneNumber: "+2348037001011",
    email: "samuel.ekanem@example.com",
    password: "Password123",
  },
  {
    firstName: "Esther",
    lastName: "Chukwu",
    PhoneNumber: "+2348037001012",
    email: "esther.chukwu@example.com",
    password: "Password123",
  },
  {
    firstName: "David",
    lastName: "Yakubu",
    PhoneNumber: "+2348037001013",
    email: "david.yakubu@example.com",
    password: "Password123",
  },
  {
    firstName: "Helen",
    lastName: "Okafor",
    PhoneNumber: "+2348037001014",
    email: "helen.okafor@example.com",
    password: "Password123",
  },
  {
    firstName: "Michael",
    lastName: "Ojo",
    PhoneNumber: "+2348037001015",
    email: "michael.ojo@example.com",
    password: "Password123",
  },
  {
    firstName: "Blessing",
    lastName: "Eze",
    PhoneNumber: "+2348037001016",
    email: "blessing.eze@example.com",
    password: "Password123",
  },
  {
    firstName: "Peter",
    lastName: "Anya",
    PhoneNumber: "+2348037001017",
    email: "peter.anya@example.com",
    password: "Password123",
  },
  {
    firstName: "Ngozi",
    lastName: "Adekunle",
    PhoneNumber: "+2348037001018",
    email: "ngozi.adekunle@example.com",
    password: "Password123",
  },
  {
    firstName: "Joseph",
    lastName: "Ibrahim",
    PhoneNumber: "+2348037001019",
    email: "joseph.ibrahim@example.com",
    password: "Password123",
  },
  {
    firstName: "Comfort",
    lastName: "Nnamani",
    PhoneNumber: "+2348037001020",
    email: "comfort.nnamani@example.com",
    password: "Password123",
  },
];

